from PyQt5 import QtCore, QtGui, QtWidgets
import back
from mainwin import Ui_MainWindow
class Ui_Form(object):
    def ok (self):
        print("ty")
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
def message(self,title,des):
    message = QtWidgets.QMessageBox()
    message.setWindowTitle(title)
    #message.setWindowIcon(QtWidgets.QMessageBox.Information)
    message.setText(des)
    message.exec_()
def setupUi(self, Form):
    Form.setObjectName("Form")
    Form.resize(910, 318)
    self.formLayoutWidget = QtWidgets.QWidget(Form)
    self.formLayoutWidget.setGeometry(QtCore.QRect(550, 40, 281, 221))
    self.formLayoutWidget.setObjectName("formLayoutWidget")
    self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
    self.formLayout.setContentsMargins(0, 0, 0, 0)
    self.formLayout.setObjectName("formLayout")
    self.user_name = QtWidgets.QLabel(self.formLayoutWidget)
    self.user_name.setObjectName("user_name")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.user_name)
    self.username_input = QtWidgets.QLineEdit(self.formLayoutWidget)
    self.username_input.setObjectName("username_input")
    self.username_input.setText("hr")
    self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username_input)
    self.password = QtWidgets.QLabel(self.formLayoutWidget)
    self.password.setObjectName("pass")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password)
    self.pass_input = QtWidgets.QLineEdit(self.formLayoutWidget)
    self.pass_input.setObjectName("pass_input")
    self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
    #self.pass_input.setText("hr")
    self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pass_input)
    self.ip_add = QtWidgets.QLabel(self.formLayoutWidget)
    self.ip_add.setObjectName("ip_add")
    self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ip_add)
    self.ip_input = QtWidgets.QLineEdit(self.formLayoutWidget)
    self.ip_input.setObjectName("ip_input")
    self.ip_input.setText("localhost")
    self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ip_input)
    self.db_name = QtWidgets.QLabel(self.formLayoutWidget)
    self.db_name.setObjectName("db_name")
    self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.db_name)
    self.db_input = QtWidgets.QLineEdit(self.formLayoutWidget)
    self.db_input.setObjectName("db_input")
    self.db_input.setText("orcl")
    self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.db_input)
    self.login_Button = QtWidgets.QPushButton(self.formLayoutWidget)
    self.login_Button.setObjectName("login_Button")
    self.login_Button.clicked.connect(self.login_click)
    self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.login_Button)
    spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Expanding)
    self.formLayout.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem)
    self.voda_image = QtWidgets.QLabel(Form)
    self.voda_image.setEnabled(True)
    self.voda_image.setGeometry(QtCore.QRect(10, 10, 500, 300))
    self.voda_image.setText("")
    self.voda_image.setPixmap(QtGui.QPixmap("voda.png"))
    self.voda_image.setScaledContents(True)
    self.voda_image.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
    self.voda_image.setObjectName("voda_image")
    self.retranslateUi(Form)
    QtCore.QMetaObject.connectSlotsByName(Form)
def retranslateUi(self, Form):
    _translate = QtCore.QCoreApplication.translate
    Form.setWindowTitle(_translate("Form", "Form"))
    self.user_name.setText(_translate("Form", "Username"))
    self.password.setText(_translate("Form", "Password"))
    self.ip_add.setText(_translate("Form", "Host IP"))
    self.db_name.setText(_translate("Form", "Database Name"))
    self.login_Button.setText(_translate("Form", "Login"))
def login_click(self):
    tes1, tes2, tes3, tes4 = self.username_input.text(), self.pass_input.text(),self.ip_input.text(),self.db_input.text()
    if back.cred_check(tes1,tes2,tes3,tes4):
        print ("hi")
        #self.message("Credential Check","Connection Successful")
        print ("h00000i")
        '''
        self.welcomeWindow = QtGui.QMainWindow()
        self.ui= Ui_MainWindow()
        self.setupUi(self.welcomeWindow)
        self.welcomeWindow.show()
        '''
        self.ok()
        print("byr")
    else:
        self.message("Credential Check","Connection Unsuccessful")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
